In [1]:
list(range(5))

[0, 1, 2, 3, 4]

In [2]:
list(range(2,5))

[2, 3, 4]

In [3]:
list(range(0,5,2))

[0, 2, 4]

In [4]:
list(range(0,5,2)) * 2

[0, 2, 4, 0, 2, 4]

In [5]:
tmp = list(range(0,5,2))
[x for x in tmp for y in range(2)]

[0, 0, 2, 2, 4, 4]

In [6]:
list(range(5,0,-1))

[5, 4, 3, 2, 1]

In [7]:
[i*0.1 for i in range(5)]

[0.0, 0.1, 0.2, 0.30000000000000004, 0.4]

In [8]:
A = ["a","b"]
B = ["c","d"]
tmp = [x+y for x in A for y in B]
tmp

['ac', 'ad', 'bc', 'bd']

In [9]:
import numpy as np
tmp = np.zeros((3,4))
tmp

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
x =np.array([[6, 2, 3],[4, 5, 3]])
display(x)
display(x.ravel())
display(np.ravel(x))
display(x.flatten())
display(x.ravel().tolist())

array([[6, 2, 3],
       [4, 5, 3]])

array([6, 2, 3, 4, 5, 3])

array([6, 2, 3, 4, 5, 3])

array([6, 2, 3, 4, 5, 3])

[6, 2, 3, 4, 5, 3]

In [11]:
# Deleting duplicates
# With sorting
tmp = x.ravel().tolist()
tmp = np.unique(tmp)
print(tmp)

[2 3 4 5 6]


In [12]:
# deleting duplicates
# No sorting
from collections import OrderedDict
tmp = x.ravel().tolist()
tmp = OrderedDict.fromkeys(tmp)
print(tmp)
list(tmp)

OrderedDict([(6, None), (2, None), (3, None), (4, None), (5, None)])


[6, 2, 3, 4, 5]

In [13]:
arr = [23, 6, 22, 3, 38, 15]
# Number of matching elements
n = sum(x>10 for x in arr)
print(n)
n = sum(1 for x in arr if x>10)
print(n)
n = sum([1 for x in arr if x>10])
print(n)
n = len([1 for x in arr if x>10])
print(n)

4
4
4
4
